blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  payment:
    secretEnv: ${bb_env}
  reference-data-service:
    service-host:
      host: reference-service.${bb_env}.${url}
      port: 443
      scheme: https

management:
  server:
    port: ${bb_health:8981}
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  main:
    banner-mode: "off"
  datasource:
     ***REMOVED***
    username: ${bb_db_username:developer}
    url: jdbc:postgresql://${RDS_HOSTNAME}:5432/${bb_database:-bb_dev}?currentSchema=payment&sslmode=verify-full

server:
  port: ${bb_port:8980}

